### PR TITLE
Also symlink the /usr/share directory

### PR DESCRIPTION
**Pull request by alexharv074**
This fixes a failing test.

### CODE REVIEW

**Comment by alexharv074** [comment]
Hi @carlossg   Any chance I could get this one looked at?

**Comment by alexharv074** [comment]
ping @carlossg

**Comment by alexharv074** [comment]
Hi @carlossg   If you don't have time to maintain here, any chance I could have write access?

**Comment by carlossg** [comment]
Sorry, I no longer have the time, just gave you write access. Cheers!

**Comment by alexharv074** [comment]
Thanks @carlossg

**Pull request merged**
